files:
  - source: /bundles/org.openhab.binding.openweathermap/**/i18n/**/*.properties
    ignore:
      - /bundles/org.openhab.binding.openweathermap/**/i18n/**/*_*.properties
    translation: /%original_path%/%file_name%_%two_letters_code%.properties
